### ISSUE TITLE
Need single audio at a time

### ISSUE THREAD

**Issue by swapnilchincholkar** [danielstern/ngAudio#102]
I have ng-repeat which repeats through the audio urls & in every row I have added audio.play(), when user clicks multiple play buttons all audios are played simultaneously. 

Didn't found anything which can stop currently playing audio & plays only latest clicked one. How can we do that? i.e I want only 1 audio should be played at a time.

**Comment by mgamsjager** [comment]
Guess a shares audio variable which gets set by an item in the ngrepeat

**Comment by danielstern** [comment]
Can you share a fiddle?

**Comment by itsgg** [comment]
```javascript
'use strict';

angular.module('myApp').factory('audioPlay', function ($rootScope, ngAudio) {
  return function(link) {
    if ($rootScope.currentAudio) {
      $rootScope.currentAudio.stop();
    }
    $rootScope.currentAudio = ngAudio.load(link);
    $rootScope.currentAudio.play();
  };
});
```

Use audioPlay('audio.mp3');

**Comment by danielstern** [comment]
I would be happy to have a look at a PR for this

**Comment by kpennell** [comment]
@itsgg Did you have any luck getting this to work?  I'm trying to use this for a ionic app streaming soundcloud but it only works when the phone is not on silent.  Since a lot of people have their phones on silent, this doesn't work.
