### ISSUE TITLE
License for Bower WebJars

### ISSUE THREAD

**Issue by migo** [danielstern/ngAudio#103]
Hi,

I'd like to use ngAudio with WebJars. 
This should normally be no problem, since WebJars can simply use the bower.json file and create a WebJar from this definition automatically.
However, WebJars complains that there is no license defined for ngAudio.

Can you add a LICENSE file in the root of the repository and/or define the license in the bower.js file for this purpose?

Thank you!
Michael

**Comment by danielstern** [comment]
Hey @migo ,

Sounds good! Would you be able to open a pull request with an appropriate license added?

Cheers,
DS

**Comment by migo** [comment]
Thank you, it works now!
