### ISSUE TITLE
Is the library hosted somewhere? Which file do I have to use?

### ISSUE THREAD

**Issue by FranzSkuffka** [danielstern/ngAudio#105]
I am trying to include this in a codpen pen. This library is not hosted anywhere is it? Maybe a deployment branch would be great so that everyone could access it through rawgit.

**Comment by danielstern** [comment]
Hey Franz

This library his hosted on Bower - bower install angular-audio

**Comment by FranzSkuffka** [comment]
Thanks. I only got recently into bower :sweat_smile:. Updated the readme in case someone else wonders.
https://github.com/danielstern/ngAudio/pull/115
