### ISSUE TITLE
`setCurrentTime` and `setProgress` do not work sometimes

### ISSUE THREAD

**Issue by unaizalakain** [danielstern/ngAudio#106]
It seems that the global `audio` var that both use is sometimes undefined.

I create a `NgAudioObject` using `ngAudio.load()` inside my controller. Then, inside my controller still, I try to `setCurrentTime` on it, but the global `audio` var is not yet defined. If, let's say, I tie my `NgAudioObject` to window, I can afterwards successfully set it through there. Any idea about what's happening?

**Comment by danielstern** [comment]
Could you share a JSFiddle reproducing the issue?

**Comment by unaizalakain** [comment]
Here you go: https://jsfiddle.net/vdLxhgwg/

**Comment by danielstern** [comment]
It looks like Angular is not defined inside the fiddle. https://jsfiddle.net/vdLxhgwg/

**Comment by AjejeBrazorf** [comment]
I have the same issue, did you find out how to resolve it?

**Comment by unaizalakain** [comment]
No, sorry, I decided to use [HTMLMediaElement](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement) directly: https://github.com/GISAElkartea/amv2/blob/master/antxetamedia/static/js/player.js

**Comment by kpennell** [comment]
Ran into the same issues here. 

`angular.js:13642 TypeError: vm.songObject.setProgess is not a function`

**Comment by kpennell** [comment]
nm...
Seems to work fine:

    vm.setPosition = function(e){
      var percent = ((e.offsetX / e.srcElement.clientWidth));
      vm.songObject.setProgress(percent);
    }
