### ISSUE TITLE
Loading icon when stream is loading.

### ISSUE THREAD

**Issue by marcelaerts** [danielstern/ngAudio#107]
Hello,

With ngAudio I'm connecting to a radio/audio stream. When I press play it takes a while to load. Is there a way to show a loader within ngAudio? This is just so the user knows the stream is loading. Thanks for the help.

**Comment by danielstern** [comment]
Hey @marcelaerts . This issue hasn't been looked at in some time, as browser compatibility for how loaded a file is, was not consistent last time I had a look. This would require some implementation.

**Comment by marcelaerts** [comment]
Thank you for the quick reply.
