### ISSUE TITLE
'Dismount' loaded audio object

### ISSUE THREAD

**Issue by swimclan** [danielstern/ngAudio#110]
Is there a way to dismount the audio object to clean it up out of memory if you want to load and play a totally different file (ie someone clicks a next track button in a player')?  I worry that if I simply pause the current audio and load a new audio object, I am just wasting memory on the client.  Is this what `unbind()` is supposed to do?

**Comment by danielstern** [comment]
Hey @swimclan , `unbind` removes watchers on the object, improving performance. Currently there is no unloading functionality. I'd be happy to look at PR including this functionality.

**Comment by swimclan** [comment]
OK, I may be able to propose something.  But need a better understanding of the codebase.

**Comment by mydnic** [comment]
jPlayer can handle this with its "clearMedia" method. I'm trying to do the same thing with ngAudio, but I didn't find a solution yet..
(This would be very helpful for building a multi-webradio website)

**Comment by mydnic** [comment]
Well, I just found the solution ^^ I will send a PR soon
