### ISSUE TITLE
Perfect loop

### ISSUE THREAD

**Issue by andreisamciuc** [danielstern/ngAudio#112]
Hi, I am using ngAudio to play different background songs in a Cordova app. The mp3's are short, around 10 seconds, and I play them in a loop.

But everytime the player is restarting the loop, there is ~1 second of pause between. Can I make it go continuosly?

Thanks, Andrei

**Comment by danielstern** [comment]
Hey Andrei, unfortunately support for this kind of looping varies from system to system so I don't think it can be reliably done.

**Comment by andreisamciuc** [comment]
Hi Daniel,
Thanks for taking your time to answer me. After a day of trying I managed to find a workaround for this issue, and I'm posting it as it might help someone else : 
In the angular-audio.js file, ngAudioObject module, I replaced the following line :
                    `if ($looping && audioObject.currentTime >= audioObject.duration) {`
with :

`                    if ($looping && (audioObject.duration - audioObject.currentTime) < 0.2) {`

**Comment by danielstern** [comment]
Hey Andrei, could you test this on some longer audio and if it all looks good make a PR? Also why `0.2`?

**Comment by andreisamciuc** [comment]
`That was the value where my loop started sounding good. I ran some tests, and figured out that this value will differ from sound to sound, and other developers might fight it helpful to cut more time from the loop.
So I could make a separate function inside the `audioObject`, something like `loopEager()`, but I'd rather build a `loop()` function inside the ngAudio itself, adding the possibility to cut seconds from the loop. If that is ok with you, I'll give it a go.

**Comment by danielstern** [comment]
I'd be happy to look at a PR for this
