### ISSUE TITLE
Remove $watchers for audio objects

### ISSUE THREAD

**Issue by losferwords** [danielstern/ngAudio#113]
Hello. I try to optimize my app and decrease number of watchers on my page. I preload for about 70 files use .load() method and create array of ngAudio objects. I undestand, that every object after loading has it's own $watcher. I checked  my app with snippet and find 687 watchers on page. I tried to unbind() all these objects in array and $observeProperties becomes false, but $watchers still here. After unbinding there are still 687 watchers. How can I remove watchers from loaded files and safe module functionality?

P.S. all these files just sounds and I need only play() method.

Thanks to you for this great module ;)

**Comment by danielstern** [comment]
Hey @losferwords, if all you need is the play method then you can just use the brower's native audio support.

**Comment by losferwords** [comment]
I think about it, but the main reason, why I want to use your module, it's pre-loading. I don't want to get audio file from server every time I want to play it. My way is too load all 70 files when route change complete and just play() preloaded sounds.
