### ISSUE TITLE
Global mute not worked

### ISSUE THREAD

**Issue by losferwords** [danielstern/ngAudio#116]
Hello, I think I found a bug in your module. Global functions ngAudio.mute(), ngAudio.unmute() and ngAudio.toggleMute() not working, because you set variable ngAudioGlobals.muting, but use ngAudioGlobals.isMuting. Hope I help you and you help me, please fix that))))

**Comment by losferwords** [comment]
And maybe unneeded strange variable songmuting.

**Comment by danielstern** [comment]
Hey @losferwords . Sounds good! I'd be happy to look at a PR

**Comment by olozzalap** [comment]
I am experiencing the same issue with ngAudio in my Angular app. I'm forced to .pause() the individual ngAudioObjects instead.

**Comment by boricic** [comment]
I've just ran into the same issue. Muting individual files works, but global mute doesn't.

I think @losferwords is right. I looked a bit at the global muting code and I think the wrong variables are used.

**Comment by danielstern** [comment]
@boricic Looks like it, would you be able to throw a PR together?

**Comment by boricic** [comment]
@danielstern sure, let me just take a deeper look at it, try to come up with a solution. I hope I'll find some time to do this later today.

**Comment by boricic** [comment]
There are some changes between the 1.7.1 and 1.7.2. Will you be making the 1.7.2 release tag any time soon?

Currently the latest release tag is 1.7.1, so I cannot install 1.7.2 via bower into my project.

**Comment by danielstern** [comment]
@boricic If you'd like to push the new tag, I'd be happy to make you a contributor
