### ISSUE TITLE
Sound don't play on iOs web-app opened from home screen.

### ISSUE THREAD

**Issue by HerrHansen** [danielstern/ngAudio#118]
Hi and thanx for great service.

I created a web-app with angular v1.4.5 using your ng-sound service.

All is working as expected on Mac and iPhone 4s iOs 9.1 in Chrome, Safari (normal view via address input).
When I add this app to **iPhones home-screen** and open it, no sound is played.
But only if using this:
**meta(name="apple-mobile-web-app-capable", content="yes")**
**meta(name="apple-mobile-web-app-status-bar-style", content="yes")**

Without sound is playing also on iOs Safari.

Is this issue known?
Maybe any idea how to fix?

Here is my app for reproducing (German but please just click the buttons ;-) sound should play): http://englishinsimple.com/#/stream?index=0

Thank you very much so far.

**Comment by danielstern** [comment]
Hey @HerrHansen .

Thank you very much for the original research! It looks like you are the first person to attempt using this app in this context. I'd be happy to look at a pull request. It's possible that there may be no work-around other than using the correct meta, in which case the docs could be updated.

Cheers

**Comment by rossvz** [comment]
We attempted to use our app in this same way and ran into the same issue. @HerrHansen I believe Apple actually using a slightly different browser for their home screen app. I have found no successful workaround for this yet.

**Comment by HerrHansen** [comment]
@rossvz Thank you for efforts anyway. Rock on. :-)
