### ISSUE TITLE
Possible Implemntation of HTML5 API

### ISSUE THREAD

**Issue by chrisschaub** [danielstern/ngAudio#120]
So, sometimes, randomly, songs just don't play. The songs are all up on Amazon S3 (tried Cloudfront), the url works, network is ok. I've even trapped for "error" -- not set. I've set unlock = true globally. Does error get set if you call ngAudio.play(someremotefile) with a remote file? Or do you have to do load() and then play(). Can you call ngAudio.load(someremotefile) and then ngAuido.play() without a waterfall or some sort of promise; is play() smart enough to know that a file is loading? Ok, it works 99% of time, but just sometimes drops out. Using Cordova on iOS and Android. Thanks for any pointers.

**Comment by danielstern** [comment]
Hey @chrisschaub 

That does sound like a tough one. Troubleshooting on devices is pretty tough. I would suggest doing a timeout and checking for if the song is playing, then if not, trying it again.

If you'd like the build the above feature into the library, I would be happy to look at a PR.

Cheers,
DS

**Comment by chrisschaub** [comment]
What is the best way to check if a song is playing. I see a few options.

On Sun, Dec 13, 2015 at 5:35 PM, Daniel Stern <notifications@github.com>
wrote:

> Hey @chrisschaub <https://github.com/chrisschaub>
>
> That does sound like a tough one. Troubleshooting on devices is pretty
> tough. I would suggest doing a timeout and checking for if the song is
> playing, then if not, trying it again.
>
> If you'd like the build the above feature into the library, I would be
> happy to look at a PR.
>
> Cheers,
> DS
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/danielstern/ngAudio/issues/120#issuecomment-164310654>
> .
>



-- 
Christopher Schaub
http://chris.schaub.com

**Comment by danielstern** [comment]
Hey @chrisschaub,

Best to inspect the audio object using a time-out and see if its currentTime property is what you'd expect (`>0`)

**Comment by chrisschaub** [comment]
If you haven't already, you should check out the WebAudio API. It's much
more stable than html5 audio, especially on mobile devices. I made the
switch and have not had one audio file drop out.

On Monday, December 14, 2015, Daniel Stern <notifications@github.com> wrote:

> Hey @chrisschaub <https://github.com/chrisschaub>,
>
> Best to inspect the audio object using a time-out and see if its
> currentTime property is what you'd expect (>0)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/danielstern/ngAudio/issues/120#issuecomment-164557147>
> .
>


-- 
Christopher Schaub
http://chris.schaub.com

**Comment by danielstern** [comment]
Hey @chrisschaub 

That's pretty interesting! I'd be happy to look at a pull request if you wanted to implement some WebAudio features in angular-audio (it was written before Web Audio was stable)

**Comment by chrisschaub** [comment]
I'll try. It also loads audio about twice as fast which is good.

On Tue, Dec 22, 2015 at 1:12 PM, Daniel Stern <notifications@github.com>
wrote:

> Hey @chrisschaub <https://github.com/chrisschaub>
>
> That's pretty interesting! I'd be happy to look at a pull request if you
> wanted to implement some WebAudio features in angular-audio (it was written
> before Web Audio was stable)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/danielstern/ngAudio/issues/120#issuecomment-166706384>
> .
>



-- 
Christopher Schaub
http://chris.schaub.com

**Comment by rossvz** [comment]
I would love to see if this has made any progress. @chrisschaub I'm noticing the same behavior and it's causing major roadblocks on our mobile app rollout.

**Comment by chrisschaub** [comment]
The plugin works well if you tell it to use HTML5 audio. Not quite as fast,
but more stable on iOS9.3

On Mon, Apr 11, 2016 at 2:58 PM, Ross van Zyl <notifications@github.com>
wrote:

> I would love to see if this has made any progress. @chrisschaub
> <https://github.com/chrisschaub> I'm noticing the same behavior and it's
> causing major roadblocks on our mobile app rollout.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/danielstern/ngAudio/issues/120#issuecomment-208530580>
>



-- 
Christopher Schaub
http://chris.schaub.com

**Comment by rossvz** [comment]
So HTML5 is still more stable than WebAudio? But are you still noticing the dropout behavior with HTML5?

**Comment by chrisschaub** [comment]
Right, switching this plugin to use HTML5 (a setting I think) caused the
drop outs and distortion to stop.


On Mon, Apr 11, 2016 at 3:05 PM, Ross van Zyl <notifications@github.com>
wrote:

> So HTML5 is still more stable than WebAudio? But are you still noticing
> the dropout behavior with HTML5?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/danielstern/ngAudio/issues/120#issuecomment-208532413>
>



-- 
Christopher Schaub
http://chris.schaub.com

**Comment by rossvz** [comment]
Does this currently use HTML5 by default? If not, where can I configure that? I can't seem to see anywhere where that happens

**Comment by chrisschaub** [comment]
I added this code in my

$ionicPlatform.ready(function() {
...

    // ios has audio issues
    if (navigator.userAgent.match(/(iPhone|iPod|iPad)/)) {
        //console.log('falling back to html5 audio for ios');
        window.AudioContext = null;
        window.webkitAudioContext = null;
    }


That way uses HTML5 audio on iOS where the issue occurs.


On Mon, Apr 11, 2016 at 3:08 PM, Ross van Zyl <notifications@github.com>
wrote:

> Does this currently use HTML5 by default? If not, where can I configure
> that? I can't seem to see anywhere where that happens
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/danielstern/ngAudio/issues/120#issuecomment-208533642>
>



-- 
Christopher Schaub
http://chris.schaub.com
