### ISSUE TITLE
Complete Listener keeps firing

### ISSUE THREAD

**Issue by robpolak** [danielstern/ngAudio#121]
I was using the audio.complete(function() {});  and noticed that the handler will keep firing until new audio is loaded.. is that working as expected?

Thanks

Rob

**Comment by mtalhajamil** [comment]
you can use a bool value to check if it entered the first time. then reset it while playing the next audio

**Comment by Graphfx** [comment]
Personally, to solve this issue (and for many other reasons), I set the "currentTime", the "progress" etc. to 0 when the audio is complete.

**Comment by danielstern** [comment]
PR for this would be good

**Comment by sparshy** [comment]
@Graphfx how and where are you setting that?

**Comment by sparshy** [comment]
My fix for the problem, call destroy function in callback function
			.controller('my',function(ngAudio){
				var sound =ngAudio.load("assets/voiceover-122308-asset.mp3");
				sound.play();
				sound.complete(function(audio){
					audio.destroy();
					console.log('done');
				})
			})

**Comment by techhysahil** [comment]
Complete event is firing multiple time at start of track and firing unlimited times at end of track.
