### ISSUE TITLE
Get callback for audio loading end

### ISSUE THREAD

**Issue by mtalhajamil** [danielstern/ngAudio#125]
I want to know when audio streaming is complete so that I can load the next in the sequence while the user is listening to first. Is there any method for this in your module?

Thanks in advance

**Comment by Graphfx** [comment]
You can use the "[complete](https://github.com/danielstern/ngAudio/blob/master/app/angular.audio.js#L189)" method of the NgAudioObject.
`$scope.audio.complete(callback);`

**Comment by danielstern** [comment]
This event isn't reliable 100% so the current means of checking this is running a test against the `progress` property.

**Comment by mtalhajamil** [comment]
Why dont you add audio.buffer? It is provided in HTML 5 audio.

**Comment by YeomansIII** [comment]
@mtalhajamil It's an open source project and fairly easy to work on, if you know a solution make a pull request!

**Comment by mtalhajamil** [comment]
@YeomansIII  I am new to programming specially with open source & version controlling software. Will try

**Comment by gugol2** [comment]
I would be very nice to have that promise for the audio loading.
