### ISSUE TITLE
Audio does not load or play in desktop Safari

### ISSUE THREAD

**Issue by YeomansIII** [danielstern/ngAudio#128]
I have seen a few other issues related to audio not autoloading/playing in iOS Safari, does this also occur in desktop Safari?  I don't need the audio to autoplay or autoload.  I am just trying to get the audio to play at all.  I have tried playing and loading through ng-click, jquery events and plain JS DOM events with still no luck.  The canPlay variable is always undefined on desktop Safari and I am never able to load or play the track even WITH user interaction.

Thanks.

**Comment by danielstern** [comment]
@YeomansIII Performance on Safari is spotty. I would say try it and take note of any specific problems you have as issues.
