### ISSUE TITLE
Doesn't work right on Ionic app

### ISSUE THREAD

**Issue by kpennell** [danielstern/ngAudio#130]
Not sure exactly what's going wrong here but it won't play right on a basic ionic IOS app. The sound will only play If the ringer is set to not silent but if it's set to silent and the sound won't play at all.

**Comment by kpennell** [comment]
Trying to play 30 second clips from spotify api.  Works fine on everything but when the ringer is set to vibrate/silent.

**Comment by danielstern** [comment]
Did you find a solution?

**Comment by kpennell** [comment]
No, I'm in the process of switching to cordova media plugins.

**Comment by kpennell** [comment]
@danielstern Have you seen ways to make this work for native audio on an iOS app?  I can't the cordova media plugins to work.

**Comment by danielstern** [comment]
Hey @kpennell Unfortunately I don't have any experience using this library natively on IOS

**Comment by kpennell** [comment]
no prob
