### ISSUE TITLE
Add web page to Github repo 

### ISSUE THREAD

**Issue by ripper2hl** [danielstern/ngAudio#132]
For example --> https://github.com/angular/angular.js/

![captura](https://cloud.githubusercontent.com/assets/2611201/14150704/96187abe-f667-11e5-8299-e0417cc22b5e.PNG)

**Comment by danielstern** [comment]
Looks good! How about a PR?

**Comment by ripper2hl** [comment]
click on edit button and put the webpage 
![captura](https://cloud.githubusercontent.com/assets/2611201/14191280/404a0984-f754-11e5-8e59-484bd0e83e38.PNG)


![captura1](https://cloud.githubusercontent.com/assets/2611201/14191297/5e10bc60-f754-11e5-933f-3341faa5e233.PNG)

**Comment by danielstern** [comment]
Done! Thanks for the heads up, @ripper2hl !
