### ISSUE TITLE
ngAudio fails to load after ~10 loads on same instance

### ISSUE THREAD

**Issue by andrewatwood** [danielstern/ngAudio#133]
Building a media player and everything works perfectly up until hitting load a 10th time and then the http request just hangs - even testing on localhost.

When changing the playing file I check for an existing player, stop it, then do a load into the same rootScope variable. I've done some error checking and when it hangs, I try to wipe out the player object with destroy (which seems to do nothing) and also reset the rootScope.player to an empty string before attempting to load again with a new instance of the object.

Happens on all platforms without fail. I suspect this might come from swapping out the track in the player incorrectly and something weird is going on with the objects. Any ideas?

**Comment by rossvz** [comment]
I've been running into this issue for a few weeks now trying to find a workaround. Definitely something odd, and its inconsistent in how it fails. Can sometimes fail after 4 or 5 loads, and sometimes can fail after 30. I've noticed that on the times it fails, the audio object does not contain the "audio" native object. (So audioObject.audio is undefined, if that makes sense).

I did notice slightly better performance with ngAudio.play(url) than with ngAudio.load(url) and calling play later.

**Comment by andrewatwood** [comment]
I ended up abandoning ngAudio for everything but the Track Time filter and just using a native Audio object. Had to attach a couple listeners to get some of the same progress and readiness readings but it totally got rid of the issue. Which is super weird because of how lightweight this little framework is...went through every line looking for things that could cause this problem and nothing looked out of place. It's not as bad as you might think! Definitely recommend giving it a go.
