### ISSUE TITLE
"The element has no supported sources" when restarting stream

### ISSUE THREAD

**Issue by clshortfuse** [danielstern/ngAudio#135]
Due to this change https://github.com/danielstern/ngAudio/commit/55539a4af3b79264dccd5318db09ae9774f55eba

Now, when you try to play a stopped stream, Chrome will not know how to play it. This happens on my Chromebook on v50 and my Pixel C Chrome Browser on Android.

I'm not sure why audio.src is being changed, but essentially, this causes Chrome to destroy the audio backend and will fail when trying play the stream again. I reverted the change and everything started working again for me.

Edit: Actually. audio.src is changed and never restored to it's original value, which means Chrome is trying to play "about:blank"

Edit2: If this is the expected behavior, `audio.stop` and `audio.restart` should probably be renamed to `audio.destroy`

**Comment by danielstern** [comment]
Yes this is tricky,different people tend to want a different "stop" effect.
 I'd be happy to look at a PR. Maybe add a boolean to implement both behaviours?

**Comment by clshortfuse** [comment]
Well, I don't have a problem with stop() destroying the audio source, if that's intended behavior, but restart() doesn't work. Maybe play() should rebuild audio.src if it's been "blanked", using an internal value called originalSrc?

I worked around my issue by calling pause and then setting currentTime to 0.

Or perhaps stop(shouldDestroy)
