### ISSUE TITLE
Sound plays randomly on window reload

### ISSUE THREAD

**Issue by konstantinkrassmann** [danielstern/ngAudio#136]
Hello, 

When using my mobile phone to access our application, sometimes the sound just simply starts playing. 

After some investigation we found out, that the mobile network connection quality (Edge, H)  has an direct impact on this error. 

Inspecting the phone by chrome tools we found the following error: 

> Error: Failed to set the 'currentTime' property on 'HTMLMediaElement': The element's readyState is HAVE_NOTHING.
>     at Error (native)
>     at checkWatchers (/assets/libs/angular-audio/app/angular.audio.js:341:39)
>     at /assets/libs/angular/angular.min.js:115:1
>     at m.$eval (/assets/libs/angular/angular.min.js:126:250)
>     at m.$digest /assets/libs/angular/angular.min.js:123:365)
>     at m.$apply /assets/libs/angular/angular.min.js:127:12)
>     at /assets/libs/angular/angular.min.js:90:451

**Comment by konstantinkrassmann** [comment]
I think i just found out, what's the problem. 

As the problem totally sounds like a timing problem, i took an eye on _remoteAudioFindingService_ 

There it listens to the '_loadstart_' event and resolves the promise.
But this event just tells us, that the ressource just started loading. 

I changed it to '_canplaythrough_' and voila, bug seems to be fixed. 

This also explains why it only happens on bad internet connection, this window between "start loading" and "loading complete" is increased and leads to this error.

**Comment by danielstern** [comment]
I am worried this change might break compatibility on desktop devices.

**Comment by konstantinkrassmann** [comment]
In the PR we discussed that. It would break the functionality of applications, which what to implement some kind of buffering. I folked and changed it to fix it for me.

I'm deep enought in the code, to make the option flag thing work. 

Feel free to reject the PR
