### ISSUE TITLE
Callback when load is finish.

### ISSUE THREAD

**Issue by CaptainYouz** [danielstern/ngAudio#139]
Hi.

I'm digging into the module and try to find a solution, but i'm kind of stuck here.
Is there any way to know when the load of a file is finished ?

In my scenario, i have a player button in my view. On the first click on it, if the file is not loaded, it loads the file then play it.
But if there is a wrong url path, since i still don't have the "canPlay" or "currentTime" or "duration" information (load not finish i guess), i can not know if the ngAudio object is playable or not.

In my controller

```
scope.currentAudio = false;

function playAudio() {
  if (!scope.currentAudio) scope.currentAudio = ngAudio.load(scope.filePath);

  console.log(scope.currentAudio); 
  // here the scope.currentAudio object only have id, safeId and loop as content

  setTimeout(function() {
    console.log(scope.currentAudio); 
    // here i get the complete object with the canPlay parameter, duration, currentTime etc...
  }, 3000);
}
```

Btw: for the futur, just an idea, but it can be good to have the load function as a promise.

**Comment by alxgiraud** [comment]
Same need here. Promise should be awesome.

**Comment by goeranhomberg** [comment]
Would be happy about this, too.

**Comment by sonlichao** [comment]
+1

**Comment by davidrhoderick** [comment]
+1

**Comment by danielstern** [comment]
Hello all.

This is definitely the plan but so far no consistent API exists - basically an event is supposed to fire, but as of the last time I worked on this, it doesn't work in every browser.

Anyone who wants to take a crack at this let me know or just open a PR

**Comment by alexey-sh** [comment]
any progress?

**Comment by interludic** [comment]
Closed prematurely?

**Comment by alexey-sh** [comment]
@interludic I guess it's too hard to implement.
