### ISSUE TITLE
Large number of digests

### ISSUE THREAD

**Issue by AmitMY** [danielstern/ngAudio#141]
ngAudio is constantly running $apply, as a default every 25 milliseconds.
This is because:
`var interval = $interval(checkWatchers, ngAudioGlobals.performance);`

A quick fix would be:
`var interval = $interval(checkWatchers, ngAudioGlobals.performance, true);`

But everything won't work...

---

How can you see it? easy.
1 - Go to your demo http://danielstern.github.io/ngAudio/#/
2 - Download batarang https://chrome.google.com/webstore/detail/angularjs-batarang/ighdmehidhipcmcojjgiloacoafjmpfk?hl=en
3 - Run batarang and see the amount of digests.

---

Why is it bad?
A $digest must run on every change, yes, but if there are no changes the digest is just a CPU hog.
Without angular-audio, my program has 5 digests every 30 seconds. With it, it has 2500.

---

How to fix?
I am not sure. you have to not always invoke an apply, but running a digest on every change.
This fix deserves a new version, 2.0 - because it won't 100% be compatible with every angular-audio setup.

---

**If you read so far, please comment your thoughts, or if you are a developer on this repository, can you fix it?**

**Comment by danielstern** [comment]
I'd be happy to look at a PR for this

**Comment by AmitMY** [comment]
I'm sorry, but what do you mean by PR?

**Comment by danielstern** [comment]
@AmitMY PR refers to Pull Request. Please see if you can fix the problem and if you can open a Pull Request with the changes, cheers

**Comment by AmitMY** [comment]
I'm not that good :)
Sorry, hope some day you will fix it.
Someone just used it in my project, so I looked to see if it is fixable, and it's not easy.
I opted out, because my needs are just a native audio play, no need for a dependency.

Thanks for the response, and sorry I can't help
