### ISSUE TITLE
Htaccess file problem

### ISSUE THREAD

**Issue by vikkio88** [danielstern/ngAudio#142]
Hi, I experienced a problem using this package after installing it with bower.
My server rewrite rules were overwritten by the file https://github.com/danielstern/ngAudio/blob/master/app/.htaccess and were giving me an error on production, basically a 404 when I was requiring the js with the package.
I had to delete the file from the remote folder in order to make it work.

Probably would be better to minify the scripts and leave them in the root of this folder or in a dist folder as common practice.

**Comment by danielstern** [comment]
I'd be happy to look at a PR regarding this

**Comment by vikkio88** [comment]
Why closed? Is still an issue...
