### ISSUE TITLE
Next Release?

### ISSUE THREAD

**Issue by soumak77** [danielstern/ngAudio#145]
Any idea when the next release will be?  I'm having intermittent issues with sounds playing and wondering if any of the pending fixes will help.  I see #140 might be a good start.

**Comment by danielstern** [comment]
Hey @soumak77 I'm looking to merge #140 soon. Would you be able to give the new branch a quick test in your application and see if everything is looking good?

**Comment by soumak77** [comment]
sure, where can I pick up the build?

**Comment by danielstern** [comment]
https://github.com/ave-/ngAudio/tree/fix-audio-hangs

**Comment by soumak77** [comment]
The changes in #140 aren't being tested in my app, so I can't verify the new build.  I'll close this issue and comment on #140.
