### ISSUE TITLE
Cannot use angular variables in ng-audio-hover

### ISSUE THREAD

**Issue by estebanrolando** [danielstern/ngAudio#146]
I want to specify angular vars in ng-audio-hover, but it seems that it is not supported. The expression is not resolved.

eg:

 ng-audio-hover='{{filedir}}{{file.sound}}'

I get an error logged in the console:

GET http://localhost:3000/%7B%7Bfiledir%7D%7D%7B%7Bfile.sound%7D%7D

**Comment by danielstern** [comment]
@estebanrolando Try using the controller to compile the string and passing that to your scope
