### ISSUE TITLE
Auto Play not working on iOS or Android, Randomly stop working

### ISSUE THREAD

**Issue by thisisirfan** [danielstern/ngAudio#147]
I am trying to trigger **auto play** sound on page open, it's working perfectly fine in **desktop** but not working **mobile device**. Only works when i click once or twice. I have tried all browsers on iOS and android but same issue.

**Comment by Hirbod** [comment]
@thisisirfan this is not a bug - it's by design. iOS prohibit autoplay on pageload. It has to be triggered with a click. iOS 10 will be able to autoplay audio under special circumstances

**Comment by Hirbod** [comment]
Sorry, iOS 10 only allows autoplay from videos without audio or volume set to 0
http://appleinsider.com/articles/16/07/25/new-webkit-policies-in-ios-10-to-allow-autoplay-of-silent-videos-in-safari-pause-those-with-audio

**Comment by thisisirfan** [comment]
Hello Hirbod,
Yes, i figured it out later that day, it was new for me but i got new thing into my knowledge, Thanks for reply by the way.
