### ISSUE TITLE
Very slow print dialog show in InternetExplorer 11

### ISSUE THREAD

**Issue by chouex** [danielstern/ngAudio#154]
just browse `http://danielstern.github.io/ngAudio/` and print in IE 11

i found IE have print problem after calling `ngAudio.load`, but using chrome is fine.

    "angular-audio": "^1.7.2",

**Comment by danielstern** [comment]
Hmm, link please?

**Comment by chouex** [comment]
http://danielstern.github.io/ngAudio/

the home page could reproduce the issue

**Comment by danielstern** [comment]
Print dialog seems to work fine from my workstation on this site
