### ISSUE TITLE
Using ngAudio as a global player within a player wrapper directive

### ISSUE THREAD

**Issue by phil-hudson** [danielstern/ngAudio#156]
Hey there.

I'm having some trouble using ngAudio as a global player (singleton). I've created a player component that will interact with ngAudio but am struggling with scoping and duplicate scope. I'm finding that when loading/playing new tracks, instead of replacing the existing track a new track will be added.

Basically:

I want to be able to interact with ngAudio as a singleton from a directive scope.

Do you have any examples of how this can be achieved please?

Thanks :D

**Comment by Ilya-Hubich** [comment]
Hi.
I'm also inetresting in ability to use ngAudio as a global player (singleton).
And i wanna have only one "Audio" instance or the way to destroy it.
