### ISSUE TITLE
Digest loop insanity

### ISSUE THREAD

**Issue by mvarshavsky** [danielstern/ngAudio#159]
Open your demo page: https://danielstern.github.io/ngAudio/#/audio

Run the following line in the console: `angular.element(document.body).scope().$watch(function() { console.log('Digesting...'); })`

**Comment by danielstern** [comment]
Unfortunately we don't have a way around this ATM. Anyone want to take a crack at solving this?

**Comment by mvarshavsky** [comment]
Perhaps there's a reason for this, but without diving deep into the code - why does anything at all need to be running when nothing's playing?

Also, why do you need `$setWatch` if everything's done on an interval anyway? For people who set "performance" higher?

**Comment by danielstern** [comment]
@mvarshavsky The sounds is constantly checked because outside user interaction's might have changed the time or volume without the component's knowledge
