### ISSUE TITLE
Wrong bower.json

### ISSUE THREAD

**Issue by smcardle** [danielstern/ngAudio#160]
Hi

I updated angular-audio and my main project bower.json shows the following version info

    "angular-audio": "^1.7.3",

However the bower.json file for angular-audio in my bower libs directory shows the following version

  "name": "angular-audio",
  "version": "1.7.0",

I have tried removed the library and reinstalling via the console which shows the following 
bower angular-audio#*           cached https://github.com/danielstern/ngAudio.git#1.7.3
bower angular-audio#*         validate 1.7.3 against https://github.com/danielstern/ngAudio.git#*

but the bower.json file still shows 1.7.0.

However... The bower.json in the github source shows 1.7.2 ???

The main issue I'm having is the same problem as issue 85 that was reported as fixed according to the release notes and the issue remarks

Release Notes v1.7.1
Fixed https://github.com/danielstern/ngAudio/issues/85

Here is what I get on my console

angular.audio.js:128 Uncaught TypeError: Cannot read property 'play' of undefinedtwiddle @ angular.audio.js:128

Then if I do anything that goes near another sound file I get this which is obviously the same error as reported in the issue

undefined:1 Uncaught (in promise) DOMException: The play() request was interrupted by a call to pause().

Any idea whats going on with downloading the latest version i.e. 1.7.3 ????

Steve

**Comment by smcardle** [comment]
Hi All

Any idea when the npm and bower installs will be updated to 1.7.3 as this version fixes the issue

**Comment by danielstern** [comment]
@smcardle If you would like to handle it I'd be happy to make you a contributor

**Comment by danielstern** [comment]
Please use NPM from now on https://github.com/bower/bower/issues/2298
