### ISSUE TITLE
Uncaught TypeError: Cannot read property 'play' of defined/play() request was interrupted by a call to pause()

### ISSUE THREAD

**Issue by shusak** [danielstern/ngAudio#161]
I have ngAudio injected into a controller then use ngAudio.play(link to sound file), but I'm calling a method on my controller from a ng-click event because I have to do work along with the sound being played (think a phone dialpad)

When called this way I get two errors in the Chrome (53.0.2785.116) Developer console :

"Uncaught TypeError: cannot read property 'play' of undefined" that is then followed by the error "Uncaught (in promise) DOMException: The play() request was interrupted by a call to pause()."

The uncaught is in the function twiddle() on the line audio.play() inside the addEventListener for "click". 

So I'm guessing I'm using it wrong or found a weird case here... 

My code in HTML:

```html
<span class="littleLeftPadding" ng-click="::dialpad.addToDial(0, '../assets/dtmf-0.mp3')" id="btnZero" ng-disabled="btnZero"><div class="num-text">0</div></span>
```

Inside my dialpadController:

```JavaScript
  self.addToDial = function(digit, sound) {
      ngAudio.play(sound);
      callService.currentCall.phoneNumber.append(digit);
  };
```

**Comment by luop90** [comment]
Use `ngAudio.load()` before `.play()`. That will fix the first error. 

To fix the "Uncaught (in promise) DOMException: The play() request was interrupted by a call to pause().", don't play the sound until it has loaded. You can either do this by assigning a variable to ngAudio(), and doing a `$scope.$watch()` on that variable, or by using a timeout.

**Comment by shusak** [comment]
I guess I'm still not doing something correctly as if I do a load first like below I'm seeing the same behavior - here it plays just fine - but the same messages show in the console.

```
  self.addToDial = function(digit, sound) {
      let tone = ngAudio.load(sound):
      tone.play(sound);
      callService.currentCall.phoneNumber.append(digit);
  };
```

If I check the tone.canPlay property in the dev console after the load it is always true, however, if I wrap the play with it (like below) it doesn't play (or enter that block from what I can tell) and says it is "undefined" if I output the value to the dev console - so I'm guessing that's resolved in a digest cycle? 

```
  self.addToDial = function(digit, sound) {
      let tone = ngAudio.load(sound):
      if (tone.canPlay === true)
           tone.play(sound);
      callService.currentCall.phoneNumber.append(digit);
  };
```

Hope that makes sense

**Comment by luop90** [comment]
ngAudio needs a second to load the sound. So instead of immediately checking `if (tone.canPlay)`, use:
`
$scope.$watch('tone.canPlay', function () {
  if (tone.canPlay)
    tone.play(sound);
}
`

**Comment by Cyriaqu3** [comment]
Hi, i don't understand exactly why, but using :
`ngAudio.setUnlock( false );`
solved this problem for me.

**Comment by danielstern** [comment]
Closed due to inactivity

**Comment by deliverymanager** [comment]
https://developers.google.com/web/updates/2017/06/play-request-was-interrupted
