### ISSUE TITLE
Volume control and Mute are not working on Ipad and other IOS devices

### ISSUE THREAD

**Issue by godwinvc** [danielstern/ngAudio#162]
Hi, I have been using this ngAudio in my project, all the features I require are working fine on all desktop and android devices. But, when coming to my iPad, the volume and mute doesn't seem to work.
I have used the following code where audio is loaded into `$scope.currentAudio` variable 
`$scope.currentAudio.volume = 0;` or `$scope.currentAudio.mute();`.

This works fine on Chrome Safari of Desktop but not on iPad. Is there anything that i'm missing in case of IOS devices? Please help me out!

**Comment by danielstern** [comment]
Unable to repro

**Comment by diegodotta** [comment]
I'm facing the same problem. You can reproduce opening the demo page on iPhone and try to mute. http://danielstern.github.io/ngAudio/

**Comment by diegodotta** [comment]
And the currentAudio.volume isn't working too (iOS devices).
For now, I'm using currentAudio.pause() when the user mutes the audio. :(
