### ISSUE TITLE
Are there any ways to make fade in and fade out? 

### ISSUE THREAD

**Issue by JaickGrin** [danielstern/ngAudio#164]

**Comment by danielstern** [comment]
Yes check the docs for the fadeIn and fadeOut property

**Comment by dariospadoni** [comment]
I did not find any reference to fadeIn fateOut property in the [doc](http://danielstern.github.io/ngAudio/#/docs)...where can I find something about it?

**Comment by danielstern** [comment]
Looks like some documentation is needed here
