### ISSUE TITLE
Angular dependencies >=1.2 < 1.5 with angular-audio 1.7.3

### ISSUE THREAD

**Issue by IceManbp** [danielstern/ngAudio#170]
Hi,

I just try to install angular-audio via bower, but I get dependencies error because I need to use angular 1.5.8.
On bower.json on git, angular-audio require angular >=1.2 < 1.6. But if you try to run command "bower info angular-audio" you get this bower.json

`
{
  name: 'angular-audio',
  version: '1.7.3',
  description: 'Total awesomeness for playing sounds in AngularJS',
  main: 'app/angular.audio.js',
  homepage: 'http://danielstern.github.io/ngAudio/',
  repository: {
    type: 'git',
    url: 'git://github.com/danielstern/ngAudio.git'
  },
  ignore: [
    'app/audio/*.*'
  ],
  dependencies: {
    angular: '>=1.2 < 1.5'
  },
  devDependencies: {
    jquery: '~2.1.4',
    'ui-router': '~0.2.15',
    bootstrap: '~3.3.5'
  }
}
`

**Comment by danielstern** [comment]
Bower is deprecated, try NPM
