### ISSUE TITLE
Audio play() is not working for mobile devices

### ISSUE THREAD

**Issue by rashid-sds** [danielstern/ngAudio#171]
Error: undefined is not an object (evaluating '$scope.currentAudio.paused')

i have commented global event: 
        //window.addEventListener("click",function twiddle(){
            //    audio.play();
            //    audio.pause();
            //    window.removeEventListener("click",twiddle);
            //});

Issue seems only for mobile devices.

**Comment by reinvanleirsberghe** [comment]
+1

**Comment by nncl** [comment]
+1
