### ISSUE TITLE
Digest trigger all over again

### ISSUE THREAD

**Issue by Augus** [danielstern/ngAudio#179]
Digest trigger all over again when checkWatchs, that do not make sense.
`var interval = $interval(checkWatchers, ngAudioGlobals.performance);`

To fix this problem, plaease add params to $interval
`var interval = $interval(checkWatchers, ngAudioGlobals.performance, 0, false);`

**Comment by djuerges** [comment]
Please reopen, we also faced this issue on a web project, leading to HUGE performance impacts for our customers and effectively rendering our software unusable. While there is actual work for the client to do, we are around 15-20 digest cycles per second. With this bug, while being idle the digest cycles skyrocketed up to 120! cycles per second, when using ngAudio.load

**Comment by danielstern** [comment]
PR please

**Comment by djuerges** [comment]
Hey there, it was already posted by my colleague above. https://github.com/mindsmash/ngAudio/commit/0c512a00555426e56b40e5328e4eb44037b0d02b

However there is still a memory leak for IE11 due to the internal implementation of setInterval, so we ended up not using this library any more.
