### ISSUE TITLE
ngAudio not working with Angular 1.6.x

### ISSUE THREAD

**Issue by robpolak** [danielstern/ngAudio#182]
The library plays sounds very distorted in angular 1.6.. can you please take a look?

**Comment by robpolak** [comment]
After debugging code, it looks like there are two issues

1. audioObject.playbackRate = 0.01  instead of 1 .. I could not track down what was setting this value so low.
2. Setting the audioObject.progress was causing the track to skip around, here is the code change I made:
````
 if(tempProgress  > 0 ){
              //audioObject.progress = tempProgress;  //RP .. Removed due to this resetting he progress
            }
````

**Comment by robpolak** [comment]
.. anyone .. ?

**Comment by danielstern** [comment]
Should be resolved now
