### ISSUE TITLE
What version am I on?

### ISSUE THREAD

**Issue by kmccullough** [danielstern/ngAudio#185]
I am specifying 1.7.3 in my bower.json, which corresponds to the 1.7.3 tag in your repository, but for the code at that tag, neither bower.json nor package.json have 'version' properties matching "1.7.3". Looking in `master` branch, I can see that both bower.json and package.json now have 'version' properties matching "1.7.3", but master also contains a bunch more code not in the commit referenced by the 1.7.3 tag.

So should the "1.7.3" version been referenced in bower.json and package.json at the 1.7.3 tag, but it was forgotten? Should the current version in these files in master branch be 1.7.4?

I have a fix for this issue https://github.com/danielstern/ngAudio/issues/174 , but I need to know what code to base it on (presumably master?), and I would like to know when it would be "released" in 1.7.4 (otherwise I have to use a sha).

**Comment by danielstern** [comment]
Should be resolved with latest update
