### ISSUE TITLE
When will release version 1.7.4?

### ISSUE THREAD

**Issue by Gladkiy-Alexey** [danielstern/ngAudio#188]
When will release version 1.7.4?

**Comment by danielstern** [comment]
I've just gone ahead and published it... let me know if you have any further issues!

**Comment by Gladkiy-Alexey** [comment]
Thank you.

**Comment by simonemazzoni** [comment]
Hello, I can't find the 1.7.4 version on npm. @danielstern can you please publish it?

**Comment by kamilbednarz** [comment]
I guess it was published again as 1.7.3 but under different name
https://www.npmjs.com/package/angularjs-audio

(via https://github.com/danielstern/ngAudio/issues/205)
