### ISSUE TITLE
Play sounds seamlessly on a loop

### ISSUE THREAD

**Issue by tiberiuzuld** [danielstern/ngAudio#189]
Hi @danielcrisp ,

Have an issue that the sounds are not played seamlessly, 
there's a small gap in the playback between individual loops in the current implementation of ng-audio. 
Do you think this can be improved?
There are some solutions out there (e.g. https://github.com/Hivenfour/SeamlessLoop).

Thanks

**Comment by danielcrisp** [comment]
@tiberiuzuld no idea - it's not my project :-)

**Comment by tiberiuzuld** [comment]
Ops sorry wrong Daniel :)
Wanted @danielstern :)
