### ISSUE TITLE
audio.progress is returning a string instead of a float value

### ISSUE THREAD

**Issue by niyando** [danielstern/ngAudio#192]
I am trying to add a progress slider and it doesn't move while the audio is playing. I am getting the following error in console.

`Error: [ngModel:numfmt] Expected `0.021394442795352388` to be a number`

Following is the template for my slider

```
<div class="input-group">
  <span class="input-group-addon">Progress</span>
  <input class="form-control" type="range" min="0" max="1" step="0.01" ng-model="audio.progress">
</div>
```

using the latest version 1.7.4

**Comment by niyando** [comment]
I was able to create a plunkr
https://plnkr.co/edit/y214PR3OXZ7B9LHvaeHI?p=preview

**Comment by danielstern** [comment]
Happy to look at a PR for this!

**Comment by jorgecastillo1123** [comment]
Any Updates on this

**Comment by mihaituhari** [comment]
Any release soon? I've downloaded the most recent release 1.7.4 and this still happens. Thanks

**Comment by mihaituhari** [comment]
Ok, I've found the patch on `master`, grabbed it but the audio is interrupting while playing. I'm curious what version is the demo running, as I see this issue doesn't occur.

**Comment by AndreiTelteu** [comment]
I found a solution to this ! You have to use getters and setters.
You can do this the angular way:
```html
<div class="input-group">
  <span class="input-group-addon">Progress</span>
  <input
    class="form-control"
    type="range" min="0" max="1" step="0.001"
    ng-model="audioProgressControl"
    ng-model-options="{ getterSetter: true }"
  >
</div>
```
And have this function in your controller:
```js
$scope.audioProgressControl = function (value) {
  if (angular.isDefined(value)) {
    if (Math.abs(value - parseFloat($scope.audio.progress)) < 0.001) return; // bugfix. this will prevent your player to get in a audio loop
    $scope.audio.progress = value;
  } else {
    return parseFloat($scope.audio.progress);
  }
};
```

Or you can do this in a plain javascript way. This can be better for performance.
```html
<div class="input-group">
  <span class="input-group-addon">Progress</span>
  <input class="form-control" type="range" min="0" max="1" step="0.001" ng-model="audioProgressControl.value">
</div>
```
And this function in your controller:
```js
$scope.audioProgressControl = {
  get value () {
    return parseFloat($scope.audio.progress);
  },
  set value(value) {
    if (Math.abs(value - parseFloat($scope.audio.progress)) < 0.001) return; // bugfix. this will prevent your player to get in a audio loop
    $scope.audio.progress = value;
  },
};
```

I found this answer here: https://stackoverflow.com/a/28224980/3951023
Is not perfect but gets the job done.
