### ISSUE TITLE
Not able to create multiple instances of ng audio

### ISSUE THREAD

**Issue by niyando** [danielstern/ngAudio#193]
Check this plunkr
https://plnkr.co/edit/y214PR3OXZ7B9LHvaeHI?p=preview

I have 2 different audio files being loaded in two scope variables.
Somehow, the second one overwrites the first one and I am not able to manage both individually.

The script has been taken from the latest version 1.7.4.

**Comment by john-lieb** [comment]
Hi @niyando 
This is linked to #187.
The current master branch, specifically angular.audio.js will work
