### ISSUE TITLE
Propose Logo

### ISSUE THREAD

**Issue by mirzazulfan** [danielstern/ngAudio#201]
Hi. I'm graphic disigner. I would like to know if you are interested that I make a logo for your project? If you allowed me, i"ll make logo for your project for free.
Best Regard

**Comment by danielstern** [comment]
Wow! This is super cool!! Please make a PR that adds this to the front page and I'll approve it ASAP


________________________________
Daniel Stern | CEO
Ishimura Capital Partners
________________________________

**Comment by mirzazulfan** [comment]
Thank you @danielstern .. 
![42197935-70720366-7eaf-11e8-9317-ec295a7ea74e](https://user-images.githubusercontent.com/36124339/42690791-2ba668a6-8695-11e8-96aa-f08b5c838eea.png)
What kind size you need for the logo?

**Comment by danielstern** [comment]
Hey Mirza.

I'm guessing 1024x768, set to 100% width in the Readme page would be best.

Cheers,
DS


________________________________
Daniel Stern | CEO
Ishimura Capital Partners
________________________________

**Comment by mirzazulfan** [comment]
I uploaded the files and updated the readme file. You can get the other version in [Gdrive](https://drive.google.com/drive/folders/1sr81WydzAY-ogpJcem4orhIDKcVbjCB2)
Here's the pr #202 . Thanks @danielstern 
If you need anything changes in the future, dont hesitate to contact me,
Email : mirzazulfan@gmail.com
Have a nice day.
Best regards.
