### ISSUE TITLE
firefox won't play .wav files

### ISSUE THREAD

**Issue by cmayankc** [danielstern/ngAudio#44]
Hi, I am working on an angular project where i need to play some of the .wav files, I used ngAudio for this. Chrome works fine but firefox will keep throwing errors like,

Media resource /sounds/timer.wav could not be decoded.

It may not be an issue with ngAudio but with the .wav file or with firefox, but just posting this if anybody has any idea how to fix this?

Another error with using ngAudio in firefox is,

Error: An attempt was made to use an object that is not, or is no longer, usable 

when it ajaxes the audio file and tries to play.

**Comment by danielstern** [comment]
@cmayankc I haven't seen this error before, would you be able to set up a gist or a JSfiddle along with the Firefox version you're using?

**Comment by cmayankc** [comment]
The issue was with some of the .wav files, and others were played fine. So I think that there wasn't a problem with the library. For now, I started using .mp3 format instead of .wav which play fine in firefox and everywhere.
