### ISSUE TITLE
Fade volume on pause()/stop()

### ISSUE THREAD

**Issue by bitflower** [danielstern/ngAudio#45]
Hi, would this be possible? With an attribute for the length?

**Comment by danielstern** [comment]
@bitflower This could be implemented if the solution were lightweight and unobtrusive. Could you put together an implementation and share a gist?

**Comment by rotemtam** [comment]
+1 for the suggestion

**Comment by danielstern** [comment]
This can be implemented as follows:

`audioObject.fadeIn` (getter/setter)
`audioObject.fadeOut` (getter/setter)

`audioObject.fadeIn = 300`  (fades in over 300 milliseconds.)
`audioObject.fadeOut = 300`  (fades out over 300 milliseconds.)
`x = audioObject.fadeIn`  (x is now equal to 300)

**Comment by danielstern** [comment]
Any takers?
