### ISSUE TITLE
Audio playback should support playbackRate

### ISSUE THREAD

**Issue by dbrody** [danielstern/ngAudio#46]
It would be great if this library could support playbackRate.

We are creating an application for the vision impaired and a very big feature to them is to change playback rate (often much faster). While we have looked into screen readers, we are also looking down the path of customized audio interactions.  We would like to use this library for accessibility features within our Angular Chrome App application.

The initial thought on implementation is:
**Usage**
<button ng-audio=sounds/mySound.mp3 vol=0.5 start=0.2 rate=1.0 > Click me </button>

**Setters / Getters** (on NgAudioObject)
.setPlaybackRate(float new_rate)
.getPlaybackRate()

**Implementation**
Analogous to setting and updating volume of an audio file.

Let me know all your thoughts. I will be developing this over the next few days and would love any input.

**Comment by danielstern** [comment]
This looks good. Looking forward to seeing the pull request.

Please also update the docs in the app folder.

Cheers!

**Comment by danielstern** [comment]
Any progress on this @dbrody?

**Comment by danielstern** [comment]
Actually one thought, instead of:

`.setPlaybackRate(float new_rate)
.getPlaybackRate()`

Let's go with 

`audioObject.playbackRate (getter/setter)` 

With implementation as follows,

`audioObject.playbackRate = 0.8 // changes the playback rate` 
`var x = audioObject.playbackRate; // x is now equal to 0.8`

**Comment by dbrody** [comment]
I haven't had a chance to yet - other things have taken priority. We should be focusing on audio in the next 2 weeks or so. I'll get to it then unless other people want to take a crack at it. I'll post here when I start.

Sounds like a good suggestion. Looks like volume is used the same way within the directive. I'll be using the same format / pattern as the volume code.

**Comment by danielstern** [comment]
This has been resolved in version 1.5.0.

https://github.com/danielstern/ngAudio/blob/master/app/angular.audio.js#L119
