### ISSUE TITLE
Audiofile loaded plays 'window.click' event in Firefox

### ISSUE THREAD

**Issue by jordanbaucke** [danielstern/ngAudio#48]
I've noticed that if I load a file in my scope like so:

` $scope.beep = ngAudio.load('../myfile.wav')`

This method is fired when I click anywhere in the window, obviously, and it doesn't happened again as the listener is removed - 

Doesn't seem to happened in Chrome, Safari, etc. Not sure way as `window.addEventListener` should be universal?

I'm not using the directive methods, so I'm just going to comment it out.

```
        window.addEventListener("click",function twiddle(){
            audio.play();
            audio.pause();
            window.removeEventListener("click",twiddle);
        });
```

**Comment by danielstern** [comment]
duplicate: https://github.com/danielstern/ngAudio/issues/43
