### ISSUE TITLE
Add support for angular expression evaluation

### ISSUE THREAD

**Issue by Morriz** [danielstern/ngAudio#51]
Hi, your directive attributes dont work the "angular" way. It would be expected to be able to do this:

<button ng-audio="{{ sound }}" vol="{{ settings.volume }}" translate="some-translatable-string"></button>

But all of these regular use cases are not supported. Your directive also doesnt allow the translate directive in the same node.

Do you expect to fix these issues? I would love to test your updates. Tnx in advance.

**Comment by danielstern** [comment]
Hey @Morriz 

Currently I'm not as free as I'd like to be to work on this full time, so I'd recommend implementing this feature yourself in a branch and making a pull request.

Cheers.
DS

**Comment by Morriz** [comment]
Hehe. Same here. Using videogular now, since I need video as well...

**Comment by danielstern** [comment]
Leaving this up as an open issue. All are welcome to try looking into this.
