### ISSUE TITLE
Audio wont play on Chrome/Firefox for Android when loaded via scope.

### ISSUE THREAD

**Issue by KarlNewark** [danielstern/ngAudio#52]
I have set up the a function to use ngAudio.load to load a remote mp3 into an audio object, it the immediately uses ausio.play to start playing the file. 

This function is fired when the user selects a file from an ng-repeat using a ng-click event.

This works fine across all of the desktop browsers I have tried, (Chrome, Firefox and IE on Windows 8.1 and Safari / Chrome on OSX) 

I have used remote debugging and can see that all of the details within the audio object are fine, but the player seems to pause itself and will not "unpause", i can see on the network tab that around 200b of the mp3 file is downloaded and is then stopped.

The official demo of ngAudio works fine and I have been able to use ng-audio in the tags and this does work, but there is no way to control the playback with this method, right? 

Unfortunately i have not yet been able to test on mobile safari or any browser in iOS.

**Comment by danielstern** [comment]
Hey @KarlNewark 

Maintaining support for `Android` and `iOS` is an ongoing challenge because the way they implement the web audio API is constantly changing.

It sounds like if you are experiencing the issue only in one environment but not the demo, then it might be an issue with the configuration of your server.

Could you post a link to where this bug is reproduced?

**Comment by kaushikkapil** [comment]
Hi Danielstern ,
I am facing the same issue at my end, i.e. the audio plays fine on a desktop/laptop, but not on a mobile device. At the same time, the demo code seems to work fine, and I can hear the audio there on my Android device. I copied the demo code in one of my directives, and tried to see if it works. But still I see the same problem. I have created a sample for your reference on the link below:

http://test.kapilkaushik.com/#/

Regards,
Kapil

**Comment by danielstern** [comment]
Hey Kapil.

How's it going?

I would recommend that you troubleshoot the issue on your device, develop a fix, and issue a pull request.

Cheers,
DS

**Comment by kaushikkapil** [comment]
Hi @danielstern.....I am still trying to debug the issue. Will keep you updated if I find anything. When I put logs in the library code, I do see that the "audio.paused" is true, which makes me believe that somehow for mobiles the audio object is automatically going into a pause mode.

**Comment by kaushikkapil** [comment]
@danielstern .....my bad.....I was using a little older version of ngAudio...updating it to the latest version resolved the problem...it is now working on the mobile browser...thanks !

**Comment by delatorremario** [comment]
Pude resolver que funcionara en android.
Y puedo hacer que se escuche el audio en todos los navegadores que estén abierto.

var sound = ngAudio.load( 'audio/sistemadeturnos.mp3');

    $scope.myCallback = function() {
        sound.play();
    };

 $scope.$watch('turnoUltimoLlamado._id', function(newValue, oldValue) {
              $scope.myCallback();
    });

------------
antes lo tenía de la siguiente manera y no funcionaba:

$scope.sound = ngAudio.load( 'audio/sistemadeturnos.mp3');

 $scope.$watch('turnoUltimoLlamado._id', function(newValue, oldValue) {
              $scope.sound.play();
    });

**Comment by danielstern** [comment]
Puede hacho un pull request?
