### ISSUE TITLE
Is a mouseover event directive of interest?

### ISSUE THREAD

**Issue by tomsoderlund** [danielstern/ngAudio#54]
Thanks for a great framework!

I have need for mouseover sounds in my app, is that of interest for **ngAudio**? If so, how would you like it implemented - separate directive, or on `ng-audio` with some extra property?

Also, what is the purpose of the `clickPlay` property on the directive?

**Comment by danielstern** [comment]
Hey @tomsoderlund 

Regarding `clickPlay`, setting it to false explicitly will disable the ng-audio directive from playing on click. 

https://github.com/danielstern/ngAudio/blob/master/app/angular.audio.js#L20

This is undocumented and not amazingly useful, though it is useful in the hover context being discussed.

You could implement the hover directive as follows,

`<button ng-audio='sound.mp3' ng-audio-hover>` 

And have elements with the `ng-audio-hover` play on hover, not click.

Cheers

**Comment by danielstern** [comment]
Actually, let's go with 

<button ng-audio='sound.mp3' ng-audio-hover='sound2.mp3'>

So one can set different sounds on the same element

**Comment by tomsoderlund** [comment]
Makes sense! I actually wanted to do exactly that.

**Comment by danielstern** [comment]
This is resolved as of 1.6.2
https://github.com/danielstern/ngAudio/blob/master/app/angular.audio.js#L40
