### ISSUE TITLE
Streamline way to load multiple formats

### ISSUE THREAD

**Issue by honkskillet** [danielstern/ngAudio#55]
Lets say I want to load a sound, but I'm not sure which format the browser supports.  Currently I do...

```
var nextSound = ngAudio.load("assets/audio/boxingBell.aiff");
if(!nextSound.canPlay)
      nextSound = ngAudio.load("assets/audio/boxingBell.wav");
```

Is that the recommended way to handle this?

**Comment by danielstern** [comment]
I'm not sure about this one. Is it possible to detect what sound files are supported with Javascript? :house_with_garden:

**Comment by honkskillet** [comment]
There is canPlayType()
http://www.w3schools.com/tags/av_met_canplaytype.asp
Maybe there could be a load() method which takes an array of files paths and iterates over the array until it finds a valid format.  It may also be a good idea to check internal value of the loaded sound object such as canPlay or duration to make sure the sound file actually loaded.

**Comment by danielstern** [comment]
The first argument should be modified to allow an array as the input. If it's an array, then the app should work through the array starting at the beginning.

First it should split the string to see what the extension is, before loading it, and see if that extension can play. If so, load that one, if not, move on to the next.

The first argument must still behave the same way if the input is a string.

:sun_with_face:

**Comment by SDries** [comment]
Hi, is there any news on this?
I would really love to be able to drop in an array or object of some kind with urls to files that need preloading.

What's currently the best way to do this? I suppose loop over my array||object and load each separately?

**Comment by danielstern** [comment]
Hey @SDries,

As different browsers support different formats, this is a somewhat tricky issue to solve. If you want to tackle it I'd be happy to look at a PR.

Cheers
