### ISSUE TITLE
Very Huge CPU consumption

### ISSUE THREAD

**Issue by ArTiSTiX** [danielstern/ngAudio#58]
I'm very sorry to inform you that i have no word to describe the amount of CPU your library is using...
I'm pretty sure if my i7 wasn't an 8-thread CPU, it would use 100%...

So i investigated the causes of such an issue, and i found many ones.

1. You use a watch with a deep compare
2. This watch is a function
3. You use rootScope to watch something out of $scope... Perfectly useless since digest cycle can't be smartly triggered...
4. You use a very short time interval trigger (25ms.... 40Hz, even most video games can't refresh so quickly)
5. On each interval trigger, you deregistrate your $watch, and then, create it again... (since normal digest cycle are far slower). My GC is becoming crazy
6. The whole factory code is an indirect proxy to HTML Audio element methods... You store a duplicate of Audio object state, and watch, and then you apply the changes to the original element... I'm very curious: Why don't you simply call the element methods ?
7. The $interval is called as soon as the audio is loaded, until... the close of window. Even if my controllers are destroyed, or if the sound isn't even playing... we have a 40Hz greedy cycle.
8. And the best part... Every point above is for only 1 audio element... If you dare load a second one... or more (even if it's the same file), you doubles the amount of cycles... And your CPU dies.

I try to do my best to be the most friendly as i can. *(edit: i'm a bit angry about this lib, i found no better way to show it than being such offensive)*

NB: You shall not use angular prefix "ng" for unofficial projects. This is really recommended to avoid them in case official project tends to implement it.

**Comment by honkskillet** [comment]
You weren't trying very hard to be friendly.  Specifically, "But please, learn to code" is a pretty dickish thing to say.
That being said, it does sound like these should be addressed.

**Comment by ArTiSTiX** [comment]
Yup, i agree. I'm pissed off when i see such code across the Web, especially when it makes me losing my time. And I am totally an assh*le about it. Now, if people don't appreciate my harsh honesty, this is maybe i neither want to be too helpful nor too kind. If i was, i would have proposed a solution myself.

Thanks for your comment. I'm about to edit my issue, I suppose I lost my cool.

**Comment by danielstern** [comment]
Closing due to innappropriate language

**Comment by Oza94** [comment]
And do you plan to do something about the *innapropriate* pieces of code he pointed out?
