### ISSUE TITLE
Sound plays twice on click

### ISSUE THREAD

**Issue by ncocacola** [danielstern/ngAudio#59]
Hi,

I have a piece of code that goes like this:
```html
<button ng-audio="audio/alert.mp3">
    Test
</button>
```

When I click the `Test` button, `alert.mp3` gets played twice instead of once.

I have looked through the code in `angular.audio.js`, and I found these lines:
```javascript
$element.on('click', function() {
    if ($scope.clickPlay === false) {
        return;
    }
    audio.audio.play();

    audio.volume = $scope.volume || audio.volume;
    audio.loop = $scope.loop;
    audio.currentTime = $scope.start || 0;
    $timeout(function() {
        audio.play();
    }, 5);
});
```
When I comment out `audio.audio.play()`, the sound plays only once as expected, and the same behaviour occurs if I comment out the `$timeout` section, but leave `audio.audio.play()` uncommented.

Is it normal behaviour for the alert to be played twice by default, or am I missing something?

**Comment by danielstern** [comment]
This is a bug in an older version of the library, I believe. I'd say throw together a fiddle with the bug in reproducible format.
