### ISSUE TITLE
Update Angular dependency

### ISSUE THREAD

**Issue by AaronBuxbaum** [danielstern/ngAudio#61]
Currently `ngAudio` depends on `angular#~1.2.23` which resolves to v1.2.28. Most up-to-date packages are up to the most recent stable version of Angular (~1.3), resolving to v1.3.15. I'm using ngAudio and Angular 1.3.15 and haven't seen any issues, but it'd be nice if it was officially supported. Also, it runs into a bunch of unnecessary console spam about angular version resolving:

```
Please note that,
   ngAudio#1.6.2 depends on angular#!1.2.23 which resolved to angular#1.2.28
   <a bunch of other packages> depends on angular#~1.3.8 which resolved to angular#1.3.15
Resort to using angular#1.3.15 which resolved to angular#1.3.15
Code incompatibilities may occur.
```

**Comment by danielstern** [comment]
Thank you very much for opening this issue. Would you please be able to submit this fix in a PR? Sorry but I think you would probably be able to implement the fix better than me anyways. Cheers!

**Comment by AaronBuxbaum** [comment]
For my purposes, I haven't done any fixing at all besides for bumping the angular requirement up. For my use, that doesn't break anything, but it could very well break things that I'm not aware of. I'm happy to submit a PR, but it won't be tested up to the standards you probably use.

To do the update yourself: go to your `bower.json` file and change where it says `"angular": "~1.2.23"` to `"angular": "~1.3.15"`

**Comment by Kerumen** [comment]
:+1:

**Comment by danielstern** [comment]
Resolved
