### ISSUE TITLE
Missing "ignore" entry in bower.json

### ISSUE THREAD

**Issue by AaronBuxbaum** [danielstern/ngAudio#64]
When including `ngAudio` from bower, the following warning is thrown:

`bower ngAudio#~1.6.2              invalid-meta angular-audio is missing "ignore" entry in bower.json`

While this obviously doesn't break anything, it'd be easy to include an empty `ignore` entry to avoid the warning being thrown. Should only take a minute to fix it!

**Comment by danielstern** [comment]
Looks good. You are clear to submit a PR

**Comment by danielstern** [comment]
fixed
