### ISSUE TITLE
Need a simple way to execute code when audio is playing and ended

### ISSUE THREAD

**Issue by sbollers** [danielstern/ngAudio#65]
We were using angular-media-player which exposes properties like player.playing and player.ended so that we could setup a $scope.$watch execute some code when that happened. Using ngAudio I tried similarly to setup a watch on audio.progress but it didn't work. Suggestions?

**Comment by danielstern** [comment]
@sbollers Watch on progress should work, are you testing this in a local environment without proper MIME-type support?

Could you create a JSFiddle and link to it in this issue with the bug reproduced?

**Comment by sbollers** [comment]
Ok. I reproduced it in JSFiddle: http://jsfiddle.net/HB7LU/13298/ 
You can see that the newValue is coming back undefined.

**Comment by danielstern** [comment]
Hey @sbollers 

Thanks for putting up the Fiddle.

You did not have your Watch set up correctly. Here is a working version.

http://jsfiddle.net/ukaj15zk/

All the best,
DS

**Comment by sbollers** [comment]
Thanks @danielstern!
