### ISSUE TITLE
Wrong dependency include

### ISSUE THREAD

**Issue by mgohin** [danielstern/ngAudio#66]
The file included with wiredep is ```<script src="bower_components/angular-audio/angular.audio.js"></script>``` but this file doesn't exists, can you please update your bower conf ?

**Comment by danielstern** [comment]
What version are you using?

https://github.com/danielstern/ngAudio/blob/master/bower.json indicates the correct path

**Comment by mgohin** [comment]
1.6.2, last version available with bower.

Look the file : `"version": "1.6.3"`

So a new version is missing from the releases

**Comment by mgohin** [comment]
I kinda get it, looks like the path with `app/` isn't working properly.

Could you give your lib (minified) in a folder like `dist/angular.audio.js` ?

Because it's in a folder containing a demo app ...

I created a dist folder, copy/past your js file, changed bower.json :
    
    {
        "name": "angular-audio",
        "version": "1.6.2",
        "description": "Total awesomeness for playing sounds in AngularJS",
        "main": "dist/angular.audio.js",
        ...
    }

And I got a correct path in my html file `<script src="bower_components/angular-audio/dist/angular.audio.js"></script>`

**Comment by danielstern** [comment]
https://github.com/danielstern/ngAudio/issues/73
