### ISSUE TITLE
Uncaught TypeError: Cannot read property 'play' of undefined

### ISSUE THREAD

**Issue by laicosly** [danielstern/ngAudio#67]
The audio still starts playing, but console logs that error.
twiddle	@	angular.audio.js:128

```javascript
if (ngAudioGlobals.unlock) {

            window.addEventListener("click",function twiddle(){
                audio.play();
                audio.pause();
                window.removeEventListener("click",twiddle);
            });
        
        }
```

**Comment by bartvanremortele** [comment]
I'm having this exact same issue. What is the twiddle function used for?

**Comment by danielstern** [comment]
See https://github.com/danielstern/ngAudio/issues/70

**Comment by Stexxen** [comment]
@danielstern I have the same problem. 
Should 'audio' be a parameter to the callback function.
Also after reading issue #70 I am none the wiser to what this twiddle function is for.
Have you referenced the right issue?
