### ISSUE TITLE
Options cannot be set in the way docs suggest

### ISSUE THREAD

**Issue by mcwebb** [danielstern/ngAudio#68]
Hi thanks for the module, it's great!
Just thought I should say that it seems that the method of setting ```ngAudio.OPTION = 'foo'```, as suggested in the docs, doesn't actually work. I've only tested with ```ngAudio.performance``` but suspect it's the same for ```ngAudio.unlock``` too.
Instead one has to override the ```ngAudioGlobals``` value.

**Comment by danielstern** [comment]
Thank you for opening the issue. Yes, this looks like a bug. Would you be able to put together a quick pull request with the fix?

**Comment by mcwebb** [comment]
From my brief look at it I don't think it's possible to set options in that way since the service is instantiated before you have a chance to set them. I think overwriting the default value object is a perfectly acceptable way of setting the options on a global level, as such only the documentation would need to be updated.

**Comment by danielstern** [comment]
@mcwebb You have the all clear to make the necessary updates and issue a pull request. :rocket: :guitar:

**Comment by mcwebb** [comment]
#72

**Comment by danielstern** [comment]
https://github.com/danielstern/ngAudio/pull/83
