### ISSUE TITLE
Playing sequential audio files

### ISSUE THREAD

**Issue by sbollers** [danielstern/ngAudio#69]
I am currently using ngAudio to play multiple audio files sequentially. I wrote a function called asyncPlayAudio(url) that watches the progress of the audio file playing to returns a promise when it reaches 1. The calling function gets the resolved promise and then passes the url of the next file to play. The problem is that I don't have a good solution for pausing and resuming where I left off. Seems like there should be a way to load a set of audio files. Rather than creating a single audio object it would create an array of audio objects and play each one sequentially. Thoughts?

**Comment by danielstern** [comment]
Sounds like an additional service could be added to the ng-audio module to help with this sort of sequencing.

**Comment by interludic** [comment]
Is this project abandoned?

**Comment by danielstern** [comment]
It's still widely used, so no, but I'm personally taking a step back from actively maintaining it. @interludic I'm happy to give you administrator privileges, so you can make any updates you see fit.
