### ISSUE TITLE
No audio being played on an iPad when using the service

### ISSUE THREAD

**Issue by bartvanremortele** [danielstern/ngAudio#70]
Hello,

I'm having an issue where I can't seem to fix audio playing on an iPad when using ngAudio. When I use the ng-audio directive in the view everything works fine but when I try to load a sound file dynamically and play it using the ngAudio.load way it does not work.

Inside the controller

```
    $scope.playQuestion = function() {
      ngAudio.load(audioClipSrc).play();
    }
```

Inside the view:

```
<a class="btn btn-default btn-primary btn-lg" href="" ng-click="playQuestion()" role="button">Play Question</a>
```

This works in the browser but there is also an issue with it. If I press the button the audio plays, but if I press again anywhere inside of the browser the audio fragment is interrupted and does not continue to play until finished.

**Comment by danielstern** [comment]
What version of IOS is your device? IOS is being updated all the time so this library needs to be continuously updated as well. I heartily endorse troubleshooting the matter and posting a pull request with the fix.

**Comment by danielstern** [comment]
Close as inactive

**Comment by floriansemm** [comment]
Same issue here:

iOS: 10.10.4, Safari
angular-audio: 1.6.2

**Comment by danielstern** [comment]
That's a tough one. The library has recently become easier to build and deploy, so hopefully someone will be able to come up with a fix. I do not have this device currently so my hands are tied as far as troubleshooting its functionality. I encourage you to have a look and see if you can implement a solution.

**Comment by georgebatalinski** [comment]
I am on iOS 8.3, Safari 
If you want clicking enabled, you can do something like this 

```
  vm.audio = ngAudio.load(getSoundPath(vm.assessment));
  $document.on('click', function () {
    vm.playSounds();
  });

  vm.playSounds = function () {
    $timeout(function () {
      vm.audio.audio.play();
    }, 5);

  }

```

Review line 42 
https://github.com/danielstern/ngAudio/blob/master/app/angular.audio.js

**Comment by georgebatalinski** [comment]
For auto play - it maybe tough 

```
Warning: To prevent unsolicited downloads over cellular networks at the user’s expense, embedded media cannot be played automatically in Safari on iOS—the user always initiates playback. A controller is automatically supplied on iPhone or iPod touch once playback in initiated, but for iPad you must either set the controls attribute or provide a controller using JavaScript.

```

Potential solution to trigger click 
1. http://stackoverflow.com/questions/3009888/autoplay-audio-files-on-an-ipad-with-html5

**Comment by danielstern** [comment]
@georgebatalinski That is very inetersting, I've never seen the GetSoundPath method. Maybe we could implement the fixes on another branch, and then have a look at the new branch with our devices to see if things work better.
