### ISSUE TITLE
Play sounds simultaneously (in sync)

### ISSUE THREAD

**Issue by phuongvo83** [danielstern/ngAudio#71]
First of all thank you and all the other contributors for the ngAudio directive.

Currently I’m developing a page for a music site that have 24 instruments which all play the same song. The idea is that you can toggle the instruments and hear how they play together.

The site is build in Angular JS and I’m using your directive to play the instruments (mp3’s).

The setup is quite simple, I start creating a list of NgAudioObject. Then I have a function “Play All”, that plays all the sounds and mute them and another function to mute/unmute the instruments when toggling.

The problem is that the sounds don’t play well in the different browsers and sometimes a bit out of sync. In Crome its fine. But in Firefox, the sounds are lagging and in Safari the songs does not play at all. Also on the browser in iPad/iPhone, the songs starts but aren’t muted when pressing the “Play All” button. 
So my question is, is it possible to use the directive for this purpose? Maybe code it differently.

You can see the site here: http://egedalmusikskole.chopstickz.dk/#/instrumenter

I’m not the best coder in the world but I’m trying to learn to be :).

CODE SIPPETS

/* LOAD SOUND */
var soundList = [
            {
                "id": 3,
                "name":"Cajon",
                "soundUrl":"http://egedalmusikskole.chopstickz.dk/res/3.Cajon/Final OTJ cajon.mp3",
                "gifAnimation": "/res/3.Cajon/Cajon.gif",
                "gifAnimationStil": "/res/3.Cajon/CajonSH.png",
                "class": "btn-blue"
            },
            {
                "id": 24,
                "name":"Percussion",
                "soundUrl":"http://egedalmusikskole.chopstickz.dk/res/24.Percussion/Final OTJ percussion.mp3",
                "gifAnimation": "/res/24.Percussion/Percussion.gif",
                "gifAnimationStil": "/res/24.Percussion/PercussionSH.png",
                "class": "btn-blue"
            },
            {
                "id": 13,
                "name":"Marimba",
                "soundUrl":"http://egedalmusikskole.chopstickz.dk/res/13.Marimba/Final OTJ marimba.mp3",
                "gifAnimation": "/res/13.Marimba/Marimba.gif",
                "gifAnimationStil": "/res/13.Marimba/MarimbaSH.png",
                "class": "btn-blue"
            },
            {
                "id": 16,
                "name":"Steel Pans",
                "soundUrl":"http://egedalmusikskole.chopstickz.dk/res/16.Steelpans/Final OTJ steel drums.mp3",
                "gifAnimation": "/res/16.Steelpans/Steelpans.gif",
                "gifAnimationStil": "/res/16.Steelpans/SteelpansSH.png",
                "class": "btn-blue"
            } 
	    …...   
];

soundList.forEach(function (soundObj, i) {
            var sound = ngAudio.load(soundObj.soundUrl); // returns NgAudioObject  
            soundObj.audio = sound;
            instruments.push(soundObj);
});

$scope.playAll = function () {
            instruments.forEach(function (soundObj, i) {
                soundObj.audio.play();
                soundObj.audio.muting = true;
            });
};

$scope.play = function (selectedSoundObj) {
            if (selectedSoundObj.audio.muting) {
                selectedSoundObj.audio.muting = false;
            }
            else {
                selectedSoundObj.audio.muting = true;
            }
};

**Comment by danielstern** [comment]
Unfortunately the Web Audio API is not well supported and playing many tracks in sync is a challenge.
You are better off using the basic elements of the web audio API - nodes, gains, streams, etc - to build your app. 
Another idea is to use MIDI or web audio API oscillators.

**Comment by phuongvo83** [comment]
Ok i'll look into that. Thanks for the pointers :).
