### ISSUE TITLE
allow angular 1.4 as dependency

### ISSUE THREAD

**Issue by bdwain** [danielstern/ngAudio#73]
i tested angular 1.4 with this and nothing seemed to break. Can an update be released with 1.4 as an allowed dependency without bower asking for a version resolution?

**Comment by danielstern** [comment]
Makes sense to me, could you open a PR?

**Comment by bdwain** [comment]
yep. will do

**Comment by bdwain** [comment]
on second thought, i just realized my pull request will not allow angular 1.2 or 1.3. I think it'd be good to allow those. i'll open up another pull request
