### ISSUE TITLE
Many audio extensions

### ISSUE THREAD

**Issue by Pexak** [danielstern/ngAudio#77]
Is it possible to load mp3 if ogg is not supported by browser and ogg if mp3 is not supported by browser? I do not see that functionallity

**Comment by danielstern** [comment]
Hey @Pexak .

The functionality you propose is being considered.

One possible implementation would be to allow the user to pass an array instead of a string for the first argument, e.g,

`ngAudio.load(['sound1.mp3','sound1.ogg']);`

Would this work for what you're implementing?

**Comment by Pexak** [comment]
Hey @danielstern !
Thanks for answer,
it would work : )
