### ISSUE TITLE
CurrentTime

### ISSUE THREAD

**Issue by judsonbomfim** [danielstern/ngAudio#78]
How can I modify CurrentTime to the format 00:00:00 (hh: mm: ss)?
I am making an application with Ionic + angularjs

**Comment by danielstern** [comment]
Currently there is no feature that does that. However, that seems like a good idea. Perhaps an `ngAudioFormat` service.

**Comment by judsonbomfim** [comment]
It would be great, as is the standard used on a player!
There is some temporary alternative while there is an upgrade from ngAudio?

**Comment by danielstern** [comment]
I'm not sure if functionality for this exists. I would say a good solution would be to implement this and then submit a pull request.

**Comment by danielstern** [comment]
Proposed functionality loosely as follows:

`app.filter("trackTime", function(){
    return function(input){
         
        var totalSec = 0;
         
        // String manipulation
        var inputString = input ? input.toString() : "";
        for (var i = 0; i < inputString.length; i++){
            var dotIndex = inputString.indexOf(".");
            totalSec = parseInt(inputString.slice(0, dotIndex));
        }
  
        var output = "";
        var hours = 0;
        var minutes = 0;
        var seconds = 0;
         
        if (totalSec > 3599) {
             
            hours = Math.floor(totalSec / 3600);
            minutes = Math.floor((totalSec - (hours * 3600)) / 60);
            seconds = (totalSec - ((minutes * 60) + (hours * 3600))); 
             
            if (hours.toString().length == 1) {
                hours = "0" + (Math.floor(totalSec / 3600)).toString();
            } 
             
            if (minutes.toString().length == 1) {
                minutes = "0" + (Math.floor((totalSec - (hours * 3600)) / 60)).toString();
            } 
             
            if (seconds.toString().length == 1) {
                seconds = "0" + (totalSec - ((minutes * 60) + (hours * 3600))).toString(); 
            } 
   
            output = hours + ":" + minutes + ":" + seconds;
             
        } else if (totalSec > 59) {
             
            minutes = Math.floor(totalSec / 60);
            seconds = totalSec - (minutes * 60);
             
            if (minutes.toString().length == 1) {
                 minutes = "0" + (Math.floor(totalSec / 60)).toString();
            }
             
            if (seconds.toString().length == 1) {
                 seconds = "0" + (totalSec - (minutes * 60)).toString();
            }
     
            output = minutes + ":" + seconds;
             
        } else {
             
            secconds = totalSec;
             
            if (seconds.toString().length == 1) {
                secconds = "0" + (totalSec).toString();
            }
         
            output = totalSec + "s";
             
        }
 
        return output; 
    }
})`

**Comment by judsonbomfim** [comment]
Excellent!
It worked perfectly!
Thank you very much!

**Comment by danielstern** [comment]
This is set for implementation in the next major release.

**Comment by danielstern** [comment]
https://github.com/danielstern/ngAudio/pull/83
