### ISSUE TITLE
ngAudio + SoundCloud

### ISSUE THREAD

**Issue by judsonbomfim** [danielstern/ngAudio#80]
Hello! I'm using ngAudio with Soundcloud, but it is with a great delay when the squeeze play. You have a solution for this?

**Comment by danielstern** [comment]
Hey @judsonbomfim 

I'm not sure, ngAudio has never had an issue with SoundCloud. Coudl you post a link to the implementation you have?

**Comment by judsonbomfim** [comment]
The code I am using is this

<code>
app.controller('MensagensPost', function($scope, $stateParams, DataLoader, $ionicLoading, $rootScope, $sce, $timeout, ngAudio) {
	$ionicLoading.show({
		noBackdrop: true
	});

  var singlePostApi = $rootScope.url + '/wp-json/posts/' + $stateParams.postId;
	  DataLoader.get( singlePostApi ).success(function(data, status, headers, config) {
	  $scope.preletor = data.acf.preletor
	  $scope.audioLink = data.acf.link_mensagem_de_audio_mobile;
		// Soundcloud
		var audioUrl = 'http://api.soundcloud.com/resolve.json?url=' + $scope.audioLink + '&client_id=' + $rootScope.clientId;
		DataLoader.get( audioUrl ).success(function(data, status, headers, config) {
			$scope.title = data.title;
			$scope.duration = data.duration;
			$scope.downloadable = data.downloadable;
			$scope.download_url = data.download_url;
			$scope.stream = data.stream_url + '?client_id=' + $rootScope.clientId;
			$scope.sound = ngAudio.play($scope.stream);
			$timeout(function () {
				$ionicLoading.hide();
			}, 1000);
		});
    })
	.error(function(data, status, headers, config) {
      console.log('error');
    });
	$scope.$on('$ionicView.unloaded', function(){
		return $scope.sound.stop();
	});
})
</code>

**Comment by judsonbomfim** [comment]
In the browser gives no delay, but when going to phonegap build and installed on andoid, it takes about 10-15 seconds to start

**Comment by danielstern** [comment]
Hey @judsonbomfim 

Unfortunately Phonegap adds many steps in order to process Front End Code for Android. Without knowing the details of all these steps, it is impossible to know what is causing the issue.

I would suggest (if possible?) you preload the sound to work around this bug.

**Comment by judsonbomfim** [comment]
This pluglin is excellent, the best I've found. But with this error can not use it to production.
We find solution?

**Comment by judsonbomfim** [comment]
The files has about 1h. Is this the reason for the delay?
How best to run streaming?

**Comment by judsonbomfim** [comment]
nothing??

**Comment by danielstern** [comment]
Hey @judsonbomfim 

Sorry for the late reply. Unfortunately I am unable to tackle this right now so I suggest looking into the issue and opening a PR if you find a solution.

DS

**Comment by CSCG** [comment]
@judsonbomfim I've seen multiple reports of PhoneGapped applications using this module having a delay -- I've not yet had a chance to investigate further, but I do believe it's an issue with the way phonegap is porting some of these across platform. 

You are stating the file is about 1h long? I noticed on a different issue that large files / streaming files take a delay on mobile to begin play - I'm wondering if there needs to be a certain % of buffer achieved before play is activated, but again, I've not yet dug deep enough to investigate.
