### ISSUE TITLE
Method play() could return a promise allowing to execute code on play end

### ISSUE THREAD

**Issue by reda-alaoui** [danielstern/ngAudio#81]
Hello,

I know that we can `$watch` play progress, but it doesn't match my use case.

I have a very short mp3 sound.
Each time the user executes an action, the sound must be played.
Execution sequence can be really fast.
If user is fast enough he can execute his action `3 times` in a row, triggering `play()` `3 times` but hearing the sound only `2 times`. I think it's because if we hit `play()` on a sound not yet over, the command is missed.

So, what if `play()` returned a promise that would be resolved at play end?

**Comment by danielstern** [comment]
Hey Reda.

I'm not sure a promise makes sense here.

Would a method on the `audioObject`, say, `.end(cb)` work? It would sort of be like this:

    var sound = ngAudio.load('mySound.mp3');
    sound.play().end(()=>{console.log('this is the end of the sound')};

**Comment by reda-alaoui** [comment]
Hello,

A callback would be good to ;)

**Comment by JimmyLv** [comment]
@danielstern Hi, How can I auto shuffle a songs list after each song finished? Thanks you...

I use `.complete()` method but got error `Maximum call stack size exceeded`

```js
    vm.shuffle = () => {
      if (vm.audio) {
        vm.audio.pause();
        vm.audio.unbind()
      }
      vm.selectedMusic = sample(vm.musics);
      vm.audio = ngAudio.load(vm.selectedMusic.url);
      vm.audio.play();
      vm.audio.complete(vm.shuffle());
    };
```
