### ISSUE TITLE
Load and play a remore audio on mobile doesn't work

### ISSUE THREAD

**Issue by catokx** [danielstern/ngAudio#82]
I have a web service that creates an audio file on button click, after creation i need  to load and play it. On desktop it works very well, on mobile i have no audio, i had the same problem with static audio files and i solved it preloading the audio files, but with the real time service icannot

**Comment by danielstern** [comment]
Can you please share a live implementation?

**Comment by tobilg** [comment]
I think it's the same problem with the latest version of Safari on Mac OS X.
