### ISSUE TITLE
currentTime not changing on mouse event

### ISSUE THREAD

**Issue by julesmoretti** [danielstern/ngAudio#84]
Hi there first of all thank you for this great plugin it is very useful.

I am trying to change the currentTime using my left and right keys and the way I am trying to do this right now is with a keyboard event listener `window.addEventListener( 'keydown', $scope.keyboardShortcut );` and if the key is `right` or `left` then it loads the function `$scope.moveSelectionHorizontally( 'left' );`. Within this function I increased the level of complexity by identifying if someone is also holding down `shit` or `command` etc to increase or decrease the time change interval.

Long story short even though those keys seem to be called properly due to the right console.logs popping up. The following lines still does not change the currentTime at all and I have no idea why.

`$scope.audio.currentTime = $scope.audio.currentTime / 2;`
or
`$scope.audio.currentTime = $scope.audio.currentTime - 50;`
or
`$scope.audio.currentTime -= 50;`

I have a couple of $scope.$apply() in my controllers but I would hope these have nothing to do with it.

Do you have any idea why this could be the case or anything that could affect it?

I am using version 1.7.0 and do not use `unbind()` or `unlock`.

Thank you for your time!

**Comment by danielstern** [comment]
Can you share an implementation?

**Comment by lbyers** [comment]
I am not using this part of the API but at quick glance it looks like __setCurrentTime__ method is the exposed api for adjusting that property.  The trick here being I don't know how you could access the currentTime correctly from the audio object. Basically what this returns, $scope.audio.currentTime is a **private** variable that might not be trustworthy outside of the implementing class.

But it is still worth a try using the __setCurrentTime__ method:

if this works: $scope.audio.setCurrentTime($scope.audio.currentTime / 2)

then it would be easy to add a proper public interface to access that current time value.

**Comment by danielstern** [comment]
Please share a JSFiddle with your bug reproduced and we'll have a look.
