### ISSUE TITLE
Audio objects watchers are kept around after scope containing audio file is destroyed.

### ISSUE THREAD

**Issue by lbyers** [danielstern/ngAudio#88]
The NgAudioObject creates 2 watchers on the rootScope. If the audio object is destroyed those watchers leak and can shortly start eating up a lot of CPU cycles.

**Comment by lbyers** [comment]
Note the pull request for this fix only auto cleans up audio objects that are created using the directive. If a user creates an audio object manually using the ngAudio.load method, they should also manually call the destroy method on the instance whenever it goes out of scope.

**Comment by danielstern** [comment]
Maybe the object could throw a warning if it's at risk of leaking?

**Comment by lbyers** [comment]
If we could throw a warning we could just instead remove the rootScope watchers. Unfortunately (and I've tried) I cannot figure out a way for the object to know when it's scope is going to be destroyed. The audio objects don't have a notion of their "owner".  I am no Angular expert, so there may be a way I just don't know about. The audio objects won't get garbage collected because they are used by the rootScope watcher. For us the leaked memory wasn't so much of an issue as the CPU cycles being eaten up by the frequent callback executions resulting from the watch in $setWatch().

I can't see a way to fix this without changing the load and play API to allow for a $scope to be passed in. Then just assign the watchers to that scope. Then if that scope ever gets destroyed watchers are automatically removed. For backwards compatibility if it isn't passed in, it could use the $rootScope.

I'll submit a pull request with the changes and you can take a look and see what ya think.

**Comment by danielstern** [comment]
That makes sense. I like the use of `$rootScope` for backwards compatibility. Looking forward to the PR

**Comment by lbyers** [comment]
Also had to clear the interval created when the object is instantiated. But it all should happen automagically if a user passes in a scope, or uses a directive.
