### ISSUE TITLE
Update documentation to reflect API changes to load and play

### ISSUE THREAD

**Issue by lbyers** [danielstern/ngAudio#92]
the ngAudio __load__ and __play__ methods now take an optional scope object as the second parameter. If provided then the audio object will be liked to that scope and will be destroyed when that scope is destroyed. If the scope parameter is omitted then the audio object is linked to the root scope and in order to remove it the user must at some point call the __destroy__ method on the audio object.

Any audio objects created using the directives are automatically linked to the scope of the view the directive is a part of.

**Comment by danielstern** [comment]
Hey @lbyers ,

This sounds good. Would you be able to open a PR?

DS
