### ISSUE TITLE
progress/range bar starts out at 50% before jumping to 0 before play

### ISSUE THREAD

**Issue by jinpark** [danielstern/ngAudio#93]
You can see it at http://danielstern.github.io/ngAudio/#/audio/audio%7Csong1.mp3 when you refresh the page.

The progress bar starts out at 50% and goes back to 0% after the audio file has been loaded. This is probably because `audio.progress` is `undefined` at the beginning and it defaults to the default which is `(min + max)/2` I've tried setting the `value` of the range to 0 with no effect.

**Comment by danielstern** [comment]
Hey @jinpark 

Unfortunately, I'm a little busy with some other repos right now, so I recommend you investigate this and make a pull request.

Cheers,
DS

**Comment by jinpark** [comment]
Understood! I'll try to have a pr for this soon

**Comment by edezacas** [comment]
I've solved this problem adding this workaround in the checkWatchers function:
```javascript
if ($observeProperties) {
      audioObject.progress = 0; //We set initial value to 0
      
      //After we check if progress is bigger than 0, and we set
      var tempProgress = (audio.currentTime / audio.duration);
      if(tempProgress  > 0 ){
         audioObject.progress = tempProgress;
   }
```

**Comment by danielstern** [comment]
Looks good, I'd be glad to look at a pull request with the above fix.
