### ISSUE TITLE
Shoutcast/Icecast streaming

### ISSUE THREAD

**Issue by mediaboxcur** [danielstern/ngAudio#94]
I'm having an issue using ngAudio for live streaming on mobile devices...the audio takes more than a minute to start playing.

do you have a way to check the network status of a remote file or stream? to see if it's connecting or downloading?

**Comment by danielstern** [comment]
Hey @mediaboxcur 

I am not familiar with those platforms but that would probably be best accomplished with a different AJAX request. The library does support a flag for downloaded but that's not well supported in all browsers.

DS

**Comment by judsonbomfim** [comment]
some success in this matter?

**Comment by mydnic** [comment]
I'm working with an Icecast server and ngAudio and I do not have this issue... You should look at your server configuration I guess

**Comment by nadeemkhoury** [comment]
@danielstern does you library support audio streaming ?? or it's specific only for static files ??

**Comment by nadeemkhoury** [comment]
@mediaboxcur does your problem solved ?? 
or you still have this issue ??

**Comment by gellerby** [comment]
@mediaboxcur I was having similar issues (30+ second buffer time) with Icecast/Shoutcast but some changes to the Icecast server config have it down to < 1 second

**Comment by danielstern** [comment]
@gellerby Would you be able to share some details on how you were able to do this? Or better yet make a Pull Request with some updates to the `readme.MD` with any info you might have

**Comment by gellerby** [comment]
@danielstern unfortunately there's nothing we can do (as far as I know) on the client side, the changes need to be made to the buffer size on the Icecast streaming server. 

Relevant articles: [1](http://stackoverflow.com/questions/6582908/why-does-it-take-so-long-for-androids-mediaplayer-to-prepare-some-live-streams), [2](http://lists.xiph.org/pipermail/icecast/2015-September/013497.html)
