### ISSUE TITLE
Duration is NaN...

### ISSUE THREAD

**Issue by natalia-pokrovskaya** [danielstern/ngAudio#98]
Hi,

I have a strange problem with one MP3 file (created with sox, it's a concatenation of 5 different MP3 files).
audio.duration is NaN and thus progress and remaining have no correct values...
Does the problem is in my MP3 file?

Thank you for your help!

**Comment by danielstern** [comment]
Hey @natalia-pokrovskaya . It sounds like it might be the sound file. Can you share a JS fiddle / try a different sound file?

DS

**Comment by natalia-pokrovskaya** [comment]
@danielstern yes, I tried another one, created with another software and it seems to work fine!
Meanwhile, I had another problem and I see no solution for the moment. I'll created another issue on this...
