### ISSUE TITLE
Reduce digest cycles

### ISSUE THREAD

**Issue by rkingon** [danielstern/ngAudio#99]
Noticed that any pages which includes ngAudio receives a ton of performance draining digest cycles per whatever the performance value is set to.

Typically a `$watch` will only trigger when there are changes to a property. Currently, even on an idle page state, ngAudio's interval is running and performing a digest cycle. I can see how this is useful while the audio is playing, but it should not be calling `$digest` while the audio is stopped or paused.

Is it possible to only run interval or at least the digest cycle while the audio is being played?

**Comment by danielstern** [comment]
Hey @rkingon 

You can actually adjust the performance by changing the `performance` property or `unbind`ing the sounds.

http://danielstern.github.io/ngAudio/#/docs

Cheers

**Comment by rkingon** [comment]
I've defiantly played with both `performance` property & `unbind()` method. It helps for sure.

The performance drag is because of the `$interval` that runs (which the `performance` property gets dropped into). This `$interval` is always running, and at the end of each interval (no matter if anything has changed) a digest cycle gets called.

Activity monitor shows a 50% cpu usage when using the default settings & a 10% after changing the `performance` & using `unbind()`. Personally, I can live with those numbers but we have a member on the team that is adamint about reducing further if possible.

Let me know if any thoughts come to mind -- if it becomes a show stopper for us i'll dig in too and see if I can come up with anything.

Thanks!

**Comment by danielstern** [comment]
Hey @rkingon,

Unfortunately, I'm not able to fully look into this at the moment so I'd say it might make sense to fork the library and implement a solution. I'd be happy to look at PR if you come up with a solution.

Cheers,
DS

**Comment by rkingon** [comment]
as we get closer to deploying this app, I may get an opportunity to look into in - in which case i'll def provide a PR

**Comment by mentheosis** [comment]
Just in case this helps anyone, I encountered this performance problem in our app and just used this work around inside of my own appropriate listener. 10% CPU at idle was not acceptable for us. The documentation on performance and interval properties could be better.

notification = ngAudio.play("sound/cool1.mp3")
$timeout ->
	notification.destroy()
, 1000

**Comment by maddes** [comment]
`It needs to be running the watch cycle while the audio is paused, because that's how it knows the audio is still paused.`

I don't understand the need for that. 
Couldn't it figure out that it's been unpaused at the unpausing event? (like at the `.play()` function)

**Comment by danielstern** [comment]
@maddes Unfortunately since any JavaScript code that can access the DOM element where the Audio is can start it or stop it, so there are no assumptions about if it is playing or not.

**Comment by maddes** [comment]
You can override the element's .play() function.

```html
<audio id="audio" />
```

```js
var $play = document.getElementById('audio').play;
document.getElementById('audio').play = function wrapper () { 
    /* do whatever you need, then */ 
    $play();
}
```
